### PR TITLE
feat: dev_process execution flow

### PR DESCRIPTION
**Pull request by samcamwilliams**
This PR implements the rest of the `dev_process` and `dev-scheduler` flows with Converge Protocol.

The core of the mechanism is as follows:
- `dev_process` acts as a router for 'normal' AO processes. It contains a device for execution (and, optionally, a device stack for that), and a scheduler device.
- Under the hood, the process message's device (`dev_process`) swaps in/out the `dev_scheduler` or `Execution-Device` (by proxy, typically a stack, too) in order to handle requests. This allows us to have one process message, but a structured and pluggable API that contains many other devices.
- Users can post to the scheduler device by running `POST /procID/Schedule`, and get from it using the same route. This is routed to `POST|GET /procID/[messages-as-Scheduler-Device]/Schedule` by `dev_process`.
- A `next` key can be called on the scheduler device through `dev_process`. This `next` function queries the `dev_scheduler` (likely on another machine, eventually) for the assignments it needs to execute, and caches the assignments in a `priv/Scheduler` key in the root process message.
- The `Compute` key in `dev_process` (`GET /procID/Compute`) then iteratively performs computation on top of the state in order to calculate the state at the time of the slot. The `priv/Scheduler/*` cache in the message means  requests to the 'SU' are not duplicated.
- The default caching mechanism recently added to `hb_converge` should take care that we are caching the requests and responses by their IDs. We only store all the keys in the resulting state once every N messages, configurably (`process_cache_frequency` in hb_opts). This part is not e2e tested, but each component is.

The PR also adds `topics` for `?event()` calls, so that we can filter logs in a more granular style. I added custom topics for:
- `converge_core`: Execution flow tracing inside hb_converge:resolve
- `converge_internal`: Calls that `converge` makes to itself, or from the default message implementation (`dev_message`).
- `converge_result`: To see only Msg1+Msg2->Msg3 transformations.

You can run `HB_PRINT=converge_result,dev_scheduler,dev_process rebar3 eunit --test dev_process:test_device_compute_test` to see the whole flow in action. This test generates a process with a normal scheduler and two `dev_test` devices attached. It schedules two messages, then has each of the devices execute on those messages in turn. The result is a list in `Results/Already-Seen` that has the slot number for each time each device was executed, yielding `[1,1,0,0]`.

All tests, bar the hb_beamr one that is dead in `main` are passing on my machine.

Next: `dev_wasm`.

🚀

### CODE REVIEW

**Comment by samcamwilliams** [comment]
I also merged `main` into the branch, so we should be good on those conflicts mentioned in the other thread.

CC @twilson63 @TillaTheHun0 @PeterFarber @oltarasenko

**Review by twilson63 — APPROVED** [review]
Test Results

=======================================================
  Failed: 1.  Skipped: 0.  Passed: 149.

**Comment by samcamwilliams** [comment]
Yep, that's the WASM one that is failing in `main` @twilson63 due to the missing `.wasm` file. My branch didn't have the error until merging in from the mainline.

**Comment by samcamwilliams** [comment]
@twilson63 @oltarasenko 

Merged in `main` with the test updates that @oltarasenko  made for `hb_cache` . Ended up building us a generic test suite generator so that we can have each test run against each store easily. Might be useful in the future.

Also removed the dead test. I have a new set of WASM tests stashed anyway, so will add those in the next PR.

Additionally, added a benchmarking framework so we can see how it is performing. It schedules messages at ~60 per second now, and almost all of that is from RSA sig time. We could parallelize it if we want, but could also just support other key types which are faster. Something very slow is happening during execution at the moment (~3 messages/sec), but I think there is likely an easy fix. Just haven't had time to debug yet.

Current `rebar3 eunit` output:

```
======================= EUnit ========================
file "hb.app"
  application 'hb'
    module 'ar_bundles'
      ar_bundles: test_no_tags...[0.387 s] ok
      ar_bundles: test_with_tags...[0.127 s] ok
      ar_bundles: test_unsigned_data_item_id...ok
      ar_bundles: test_unsigned_data_item_normalization...ok
      ar_bundles: test_empty_bundle...[0.003 s] ok
      ar_bundles: test_bundle_with_one_item...ok
      ar_bundles: test_bundle_with_two_items...ok
      ar_bundles: test_recursive_bundle...[0.176 s] ok
      ar_bundles: test_bundle_map...[0.222 s] ok
      ar_bundles: test_basic_member_id...[0.139 s] ok
      ar_bundles: test_deep_member...[0.159 s] ok
      ar_bundles: test_extremely_large_bundle...[1.979 s] ok
      ar_bundles: test_serialize_deserialize_deep_signed_bundle...[0.872 s] ok
      [done in 4.249 s]
    module 'ar_deep_hash'
    module 'ar_timestamp'
    module 'ar_tx'
    module 'ar_wallet'
    module 'dev_cron'
    module 'dev_cu'
    module 'dev_dedup'
    module 'dev_json_iface'
    module 'dev_lookup'
    module 'dev_message'
      dev_message: get_keys_mod_test...ok
      dev_message: is_private_mod_test...ok
      dev_message: keys_from_device_test...ok
      dev_message: case_insensitive_get_test...ok
      dev_message: private_keys_are_filtered_test...ok
      dev_message: cannot_get_private_keys_test...ok
      dev_message: key_from_device_test...ok
      dev_message: remove_test...ok
      dev_message: set_conflicting_keys_test...ok
      [done in 0.027 s]
    module 'dev_meta'
    module 'dev_monitor'
    module 'dev_mu'
    module 'dev_multipass'
    module 'dev_p4'
    module 'dev_poda'
    module 'dev_process'
      dev_process: schedule_on_process_test...[0.700 s] ok
      dev_process: get_scheduler_slot_test...[0.052 s] ok
      dev_process: recursive_resolve_test...[0.029 s] ok
      dev_process: test_device_compute_test...[0.332 s] ok
      [done in 1.125 s]
    module 'dev_process_cache'
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: write and read process outputs)...[0.676 s] ok
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: find latest output (with path))...[0.115 s] ok
      hb_store: -generate_test_suite/1-fun-1- (FS: write and read process outputs)...[0.481 s] ok
      hb_store: -generate_test_suite/1-fun-1- (FS: find latest output (with path))...[0.019 s] ok
      [done in 1.521 s]
    module 'dev_process_worker'
    module 'dev_scheduler'
      dev_scheduler: status_test...[0.001 s] ok
      dev_scheduler: register_new_process_test...[0.695 s] ok
      dev_scheduler: schedule_message_and_get_slot_test...[0.061 s] ok
      dev_scheduler: benchmark_test...
        Scheduled 252 messages through Converge in 4000 ms (63.00 msg/s)
[4.010 s] ok
      dev_scheduler: get_schedule_test...[0.084 s] ok
      [done in 4.866 s]
    module 'dev_scheduler_cache'
    module 'dev_scheduler_interface'
    module 'dev_scheduler_registry'
      dev_scheduler_registry: find_non_existent_process_test...ok
      dev_scheduler_registry: create_and_find_process_test...[0.005 s] ok
      dev_scheduler_registry: create_multiple_processes_test...[0.004 s] ok
      dev_scheduler_registry: get_all_processes_test...ok
      [done in 0.021 s]
    module 'dev_scheduler_server'
      dev_scheduler_server: new_proc_test...[0.352 s] ok
      dev_scheduler_server: benchmark_test...
        Scheduled 167 messages in 2500 ms (66.80 msg/s)
[3.259 s] ok
      [done in 3.617 s]
    module 'dev_stack'
      dev_stack: transform_internal_call_device_test...[0.004 s] ok
      dev_stack: transform_external_call_device_test...[0.006 s] ok
      dev_stack: example_device_for_stack_test...ok
      dev_stack: simple_stack_execute_test...[0.014 s] ok
      dev_stack: many_devices_test...[0.069 s] ok
      dev_stack: reinvocation_test...[0.028 s] ok
      dev_stack: skip_test...[0.006 s] ok
      dev_stack: pass_test...[0.021 s] ok
      [done in 0.172 s]
    module 'dev_test'
      dev_test: device_with_function_key_module_test...ok
      dev_test: compute_test...[0.017 s] ok
      dev_test: restore_test...[0.001 s] ok
      [done in 0.027 s]
    module 'dev_vfs'
    module 'dev_wasm'
    module 'hb'
    module 'hb_app'
    module 'hb_beamr'
      hb_beamr: driver_loads_test...[0.001 s] ok
      hb_beamr: simple_wasm_test...ok
      hb_beamr: imported_function_test...ok
      hb_beamr: wasm64_test...ok
      [done in 0.013 s]
    module 'hb_beamr_io'
    module 'hb_cache'
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: store simple unsigned item)...[0.001 s] ok
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: deeply nested item)...[0.883 s] ok
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: message with list)...ok
      hb_store: -generate_test_suite/1-fun-1- (FS: store simple unsigned item)...[0.001 s] ok
      hb_store: -generate_test_suite/1-fun-1- (FS: deeply nested item)...[0.454 s] ok
      hb_store: -generate_test_suite/1-fun-1- (FS: message with list)...[0.001 s] ok
      [done in 1.679 s]
    module 'hb_client'
    module 'hb_converge'
      hb_converge: resolve_simple_test...[0.001 s] ok
      hb_converge: resolve_key_twice_test...ok
      hb_converge: resolve_from_multiple_keys_test...ok
      hb_converge: resolve_path_element_test...ok
      hb_converge: key_to_binary_test...ok
      hb_converge: resolve_binary_key_test...ok
      hb_converge: key_from_id_device_with_args_test...ok
      hb_converge: device_with_handler_function_test...ok
      hb_converge: device_with_default_handler_function_test...ok
      hb_converge: basic_get_test...ok
      hb_converge: recursive_get_test...[0.002 s] ok
      hb_converge: basic_set_test...[0.001 s] ok
      hb_converge: get_with_device_test...ok
      hb_converge: get_as_with_device_test...[0.001 s] ok
      hb_converge: set_with_device_test...[0.003 s] ok
      hb_converge: deep_set_test...[0.006 s] ok
      hb_converge: deep_set_new_messages_test...[0.009 s] ok
      hb_converge: deep_set_with_device_test...[0.011 s] ok
      hb_converge: device_exports_test...[0.002 s] ok
      hb_converge: device_excludes_test...[0.001 s] ok
      hb_converge: denormalized_device_key_test...ok
      [done in 0.100 s]
    hb_crypto: sha256_chain_test (module 'hb_crypto')...ok
    module 'hb_http'
    module 'hb_http_message'
    module 'hb_http_router'
    module 'hb_http_signature'
      hb_http_signature: trim_ws_test...ok
      hb_http_signature: sign_test...[0.011 s] ok
      hb_http_signature: verify_test...[0.011 s] ok
      hb_http_signature: join_signature_base_test...ok
      hb_http_signature: signature_components_line_test...ok
      hb_http_signature: signature_params_line_test...ok
      hb_http_signature: extract_field_msg_access_test...ok
      hb_http_signature: extract_field_bs_test...ok
      hb_http_signature: extract_field_sf_test...ok
      hb_http_signature: extract_field_error_conflicting_params_test...ok
      hb_http_signature: extract_field_error_field_not_found_test...ok
      hb_http_signature: extract_field_error_not_sf_dictionary_test...ok
      hb_http_signature: extract_field_error_sf_dictionary_key_not_found_test...ok
      hb_http_signature: derive_component_test...ok
      hb_http_signature: derive_component_error_req_param_on_request_target_test...ok
      hb_http_signature: derive_component_error_query_param_no_name_test...ok
      hb_http_signature: derive_component_error_status_req_target_test...ok
      [done in 0.073 s]
    module 'hb_http_structured_fields'
    module 'hb_logger'
    module 'hb_message'
      hb_message: basic_map_to_tx_test...ok
      hb_message: default_tx_keys_removed_test...ok
      hb_message: minimization_test...ok
      hb_message: single_layer_message_to_tx_test...ok
      hb_message: single_layer_tx_to_message_test...ok
      hb_message: match_test...ok
      hb_message: structured_field_atom_parsing_test...ok
      hb_message: structured_field_decimal_parsing_test...ok
      hb_message: binary_to_binary_test...ok
      hb_message: message_with_large_keys_test...ok
      hb_message: nested_message_with_large_keys_and_data_test...ok
      hb_message: simple_nested_message_test...ok
      hb_message: nested_message_with_large_data_test...[0.002 s] ok
      hb_message: deeply_nested_message_with_data_test...[0.002 s] ok
      hb_message: nested_structured_fields_test...ok
      hb_message: nested_message_with_large_keys_test...ok
      hb_message: signed_tx_to_message_and_back_test...[0.013 s] ok
      hb_message: signed_deep_tx_serialize_and_deserialize_test...[0.013 s] ok
      hb_message: calculate_unsigned_message_id_test...ok
      hb_message: sign_serialize_deserialize_verify_test...[0.012 s] ok
      hb_message: unsigned_id_test...ok
      hb_message: list_encoding_test...ok
      hb_message: message_with_list_test...ok
      [done in 0.111 s]
    module 'hb_metrics_collector'
    module 'hb_opts'
      hb_opts: global_get_test...ok
      hb_opts: local_get_test...ok
      hb_opts: local_preference_test...ok
      hb_opts: global_preference_test...ok
      [done in 0.012 s]
    module 'hb_path'
      hb_path: push_hashpath_test...ok
      hb_path: push_multiple_hashpaths_test...ok
      hb_path: verify_hashpath_test...ok
      hb_path: pop_from_message_test...ok
      hb_path: pop_from_path_list_test...ok
      hb_path: hd_test...ok
      hb_path: tl_test...ok
      [done in 0.021 s]
    hb_persistent: merged_execution_test (module 'hb_persistent')...[0.202 s] ok
    module 'hb_private'
      hb_private: set_private_test...[0.006 s] ok
      hb_private: get_private_key_test...ok
      [done in 0.012 s]
    module 'hb_process_monitor'
    module 'hb_router'
    module 'hb_store'
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: simple path resolution)...[0.001 s] ok
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: resursive path resolution)...ok
      hb_store: -generate_test_suite/1-fun-1- (RocksDB: hierarchical path resolution)...ok
      hb_store: -generate_test_suite/1-fun-1- (FS: simple path resolution)...ok
      hb_store: -generate_test_suite/1-fun-1- (FS: resursive path resolution)...[0.001 s] ok
      hb_store: -generate_test_suite/1-fun-1- (FS: hierarchical path resolution)...ok
      [done in 0.372 s]
    module 'hb_store_fs'
    module 'hb_store_remote_node'
    module 'hb_store_rocksdb'
      hb_store_rocksdb: -write_read_test_/0-fun-5- (can read/write data)...ok
      hb_store_rocksdb: -write_read_test_/0-fun-3- (returns not_found for non existing keys)...ok
      hb_store_rocksdb: -write_read_test_/0-fun-1- (follows links)...ok
      hb_store_rocksdb: -api_test_/0-fun-27- (list/2 lists keys under given path)...ok
      hb_store_rocksdb: -api_test_/0-fun-25- (list/2 resolves given path before listing)...ok
      hb_store_rocksdb: -api_test_/0-fun-23- (list/2 when database is empty)...ok
      hb_store_rocksdb: -api_test_/0-fun-21- (make_link/3 creates a link to actual data)...[0.001 s] ok
      hb_store_rocksdb: -api_test_/0-fun-19- (make_group/2 creates a group)...ok
      hb_store_rocksdb: -api_test_/0-fun-17- (make_link/3 does not create links if keys are same)...ok
      hb_store_rocksdb: -api_test_/0-fun-15- (reset cleans up the database)...[0.106 s] ok
      hb_store_rocksdb: -api_test_/0-fun-13- (type/2 can identify simple items)...[0.001 s] ok
      hb_store_rocksdb: -api_test_/0-fun-11- (type/2 returns not_found for non existing keys)...ok
      hb_store_rocksdb: -api_test_/0-fun-9- (type/2 treats links as simple items)...[0.001 s] ok
      hb_store_rocksdb: -api_test_/0-fun-7- (type/2 treats groups as composite items)...ok
      hb_store_rocksdb: -api_test_/0-fun-5- (resolve/2 resolutions for computed folder)...[0.001 s] ok
      hb_store_rocksdb: -api_test_/0-fun-1- (resolving interlinked item paths)...[0.001 s] ok
      [done in 1.831 s]
    module 'hb_sup'
    module 'hb_test'
    module 'hb_util'
    module 'rsa_pss'
    module 'sec'
    module 'sec_helpers'
    module 'sec_tee'
    module 'sec_tpm'
    [done in 20.079 s]
  [done in 20.079 s]
=======================================================
  All 160 tests passed.
```

**Pull request merged**
