### PR TITLE
feat(metrics): introduce Erlnag VM metrics

### PR DESCRIPTION
**Pull request by oltarasenko**
- use prometheus and prometheus_cowboy libraries to expose node metrics via /metrics endpoint;
- introduce custom `ao_metrics_collector` that allows collecting application-specific metrics (Load average and Uptime);
- introduce docker-compose setup that allows bringing up local infrastructure for Prometheus and Grafana (+ dashboard defined in JSON) on local machines

### CODE REVIEW

**Comment by oltarasenko** [comment]
Screenshot 2024-11-26 at 13 14 32
Current metrics look like this on my local machine in grafana

**Comment by bredamatt** [comment]
I recon it would be valid to introduce the Prometheus and Grafana integration during CI/CD? 
In that case, do we want to publish the metrics to our pre-existing stack, or create a separate one?

**Comment by oltarasenko** [comment]
Hi @bredamatt , Could you explain what needs to be done?

**Review by twilson63 — APPROVED** [review]
LGTM

**Pull request merged**
